# Generated by Django 3.2.6 on 2021-08-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, max_length=100)),
                ('Amount', models.IntegerField(blank=True)),
            ],
        ),
    ]
