# Generated by Django 3.2.6 on 2021-08-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Amount',
            new_name='Quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
